<?php


namespace DevelopmentBundle\Repository;

use AppBundle\Traits\RepositoryPaginatorTrait;

/**
 * CompanyCodeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CompanyCodeRepository extends \Doctrine\ORM\EntityRepository
{
    use RepositoryPaginatorTrait;
}