<?php

namespace DevelopmentBundle\Repository;

/**
 * DocumentFileRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EngineeringDocumentFileRepository extends \Doctrine\ORM\EntityRepository
{

}