<?php

namespace DevelopmentBundle\Repository;

/**
 * ProgrammingDocumentTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProgrammingDocumentTypeRepository extends \Doctrine\ORM\EntityRepository
{

}