<?php

namespace DevelopmentBundle\Repository;

/**
 * ProgrammingDocumentFileRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProgrammingDocumentFileRepository extends \Doctrine\ORM\EntityRepository
{

}