<?php


namespace AppBundle\Repository;

/**
 * ApplicantFileRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */

class ApplicantFileRepository extends \Doctrine\ORM\EntityRepository
{

}