<?php

namespace AppBundle\Repository;
use AppBundle\Entity\User;

/**
 * ApplicantCommentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ApplicantCommentRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @param User[] $users
     * @return array
     */
    public function getLatestComments($users)
    {
        $qb = $this->createQueryBuilder('tc');
        $currentDate = new \DateTime(date('d.m.y'));
        $lastWeekAt = $currentDate->modify('-7 day');

        $qb
            ->select('tc')
            ->leftJoin('tc.task', 't')
            ->where(
                $qb->expr()->orX(
                    $qb->expr()->in('t.reporter', ':users'),
                    $qb->expr()->in('t.responsibleUser', ':users')
                )
            )
            ->andWhere(
                $qb->expr()->between('tc.createdAt', ':lastWeek', ':now')
            )
            ->setParameters([
                'users' => $users,
                'lastWeek' => $lastWeekAt,
                'now' => new \DateTime('now')
            ]);

        $qb->orderBy('tc.id', 'DESC');

        return $qb->getQuery()->getResult();
    }
}
