<?php


namespace AppBundle\Repository;

/**
 * ApplicantStatusRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */

class ApplicantStatusRepository extends \Doctrine\ORM\EntityRepository
{

}