<?php

namespace AppBundle\Repository;
use AppBundle\Entity\Applicant;
use AppBundle\Entity\User;

/**
 * ApplicantDiffRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ApplicantDiffRepository extends \Doctrine\ORM\EntityRepository
{
    public function getApplicantChanges(Applicant $applicant)
    {
        $qb = $this->createQueryBuilder('ad');

        $qb
            ->select('ad')
            ->where($qb->expr()->eq('ad.applicant', ':applicantId'))
            ->setParameter('applicantId', $applicant->getId());

        $qb->orderBy('ad.id', 'DESC');

        return $qb->getQuery()->getResult();
    }
}
