<?php


namespace AppBundle\Repository;

/**
 * BookFileRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */

class BookFileRepository extends \Doctrine\ORM\EntityRepository
{

}