<?php


namespace AppBundle\Repository;

/**
 * BookGenreRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */

class BookGenreRepository extends \Doctrine\ORM\EntityRepository
{
    public function getGenresGroupedByBook()
    {
        $qb = $this->createQueryBuilder('bg');

        $qb->select('bg');

        $bookGenres = $qb->getQuery()->getResult();

        $genresGroupedByBook = [];
        foreach ($bookGenres as $genre) {
            $genresGroupedByBook[$genre->getBook()->getId()][] = $genre;
        }

        return $genresGroupedByBook;
    }
}