<?php

namespace AppBundle\Repository;
use AppBundle\Entity\Book;

/**
 * BookDiffRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BookDiffRepository extends \Doctrine\ORM\EntityRepository
{
    public function getBookChanges(Book $book)
    {
        $qb = $this->createQueryBuilder('b');

        $qb
            ->select('b')
            ->where($qb->expr()->eq('b.book', ':bookId'))
            ->setParameter('bookId', $book->getId());

        $qb->orderBy('b.id', 'DESC');

        return $qb->getQuery()->getResult();
    }
}
