<?php

namespace AppBundle\Repository;

/**
 * CategoryPriceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryPriceRepository extends \Doctrine\ORM\EntityRepository
{
}
