<?php

namespace AppBundle\Repository;
use AppBundle\Traits\RepositoryPaginatorTrait;

/**
 * ClientRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClientRepository extends \Doctrine\ORM\EntityRepository
{
    use RepositoryPaginatorTrait;

    /**
     * @param $filters
     * @param int $currentPage
     * @param int $perPage
     * @return \Doctrine\ORM\Tools\Pagination\Paginator
     */
    public function  getClients($filters, $currentPage = 1, $perPage = 20)
    {
        $qb = $this->createQueryBuilder('cl');

        $qb->select('cl');
        if (!empty($filters['client'])) {
            $qb
                ->andWhere('cl.id = :client')
                ->setParameter('client', $filters['client'])
            ;
        }

        $paginator = $this->paginate($qb, $currentPage, $perPage);

        return $paginator;
    }
}
