<?php


namespace AppBundle\Repository;
use AppBundle\Traits\RepositoryPaginatorTrait;

/**
 * InterviewRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */

class InterviewRepository extends \Doctrine\ORM\EntityRepository
{
    use RepositoryPaginatorTrait;

    public function getAvailableInterviews()
    {
        $qb = $this->createQueryBuilder('i');

        $qb->select('i');

        $qb->where('i.status != 3');

        $qb->orderBy('i.id', 'ASC');

        return $qb->getQuery()->getResult();
    }
}