<?php

namespace AppBundle\Repository;

/**
 * MedicalInstitutionCategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MedicalInstitutionCategoryRepository extends \Doctrine\ORM\EntityRepository
{
}
