<?php

namespace AppBundle\Repository;

/**
 * MonitoringHostnameRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MonitoringHostnameRepository extends \Doctrine\ORM\EntityRepository
{
}
