<?php

namespace AppBundle\Repository;

use AppBundle\Entity\MonitoringHostname;

/**
 * MonitoringRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MonitoringRepository extends \Doctrine\ORM\EntityRepository
{
    public function getLastFiveDataMonitoring(MonitoringHostname $hostname)
    {
        $qb = $this->createQueryBuilder('lfd');

        $qb->select('lfd');

        $qb
            ->where('lfd.hostname = :hostname')
            ->setParameter('hostname', $hostname->getId())
            ->orderBy('lfd.id', 'DESC')
            ->setMaxResults(5)
        ;

        return $qb->getQuery()->getResult();
    }
}
