<?php

namespace AppBundle\Repository;

/**
 * PriceIterationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PriceIterationRepository extends \Doctrine\ORM\EntityRepository
{
}
