<?php

namespace AppBundle\Repository;

/**
 * ProjectStatusRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProjectStatusRepository extends \Doctrine\ORM\EntityRepository
{
}
