<?php

namespace AppBundle\Repository;

/**
 * ProjectStageProgressRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProjectStageProgressRepository extends \Doctrine\ORM\EntityRepository
{
}
