<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Project;
use AppBundle\Entity\ProjectPassport;

/**
 * ProjectPassportRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProjectPassportRepository extends \Doctrine\ORM\EntityRepository
{
}
