<?php


namespace AppBundle\Repository;
use AppBundle\Entity\Project;

/**
 * ProjectDiffRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProjectDiffRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @param Project $project
     * @return array
     */
    public function getProjectChanges($project)
    {
        $qb = $this->createQueryBuilder('pjd');

        $qb
            ->select('pjd')
            ->where($qb->expr()->eq('pjd.project', ':projectId'))
            ->setParameter('projectId', $project->getId());

        $qb->orderBy('pjd.id', 'DESC');

        return $qb->getQuery()->getResult();
    }
}