<?php

namespace AppBundle\Repository;

/**
 * ProjectMemberRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProjectMemberRepository extends \Doctrine\ORM\EntityRepository
{
}
