<?php

namespace AppBundle\Repository;

/**
 * ProjectFlowRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProjectFlowRepository extends \Doctrine\ORM\EntityRepository
{
}
