<?php

namespace AppBundle\Repository;

/**
 * ProjectStageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProjectStageRepository extends \Doctrine\ORM\EntityRepository
{
}
