<?php

namespace AppBundle\Repository;

/**
 * ProjectPriceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProjectPriceRepository extends \Doctrine\ORM\EntityRepository
{
}
