<?php

namespace AppBundle\Repository;

/**
 * ProtocolMembersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProtocolMembersRepository extends \Doctrine\ORM\EntityRepository
{

}