<?php

namespace AppBundle\Repository;

use AppBundle\Traits\RepositoryPaginatorTrait;

/**
 * SpecificationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SpecificationRepository extends \Doctrine\ORM\EntityRepository
{
    use RepositoryPaginatorTrait;

    /**
     * @param $filters
     * @param int $currentPage
     * @param int $perPage
     * @return \Doctrine\ORM\Tools\Pagination\Paginator
     */
    public function getAvailableSpecification($filters, $currentPage = 1, $perPage = 20)
    {
        $qb = $this->createQueryBuilder('sp');

        $qb->select('sp');

        $qb->where($qb->expr()->isNull('sp.deleted'));

        if (!empty($filters['project'])) {
            $qb
                ->andWhere('sp.project = :project')
                ->setParameter('project', $filters['project'])
            ;
        }

        $paginator = $this->paginate($qb, $currentPage, $perPage);

        return $paginator;
    }
}