<?php

namespace AppBundle\Repository;

/**
 * TaskResultRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TaskResultRepository extends \Doctrine\ORM\EntityRepository
{

}