<?php

namespace AppBundle\Repository;

use AppBundle\Traits\RepositoryPaginatorTrait;

/**
 * AchievementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserAchievementRepository extends \Doctrine\ORM\EntityRepository
{
    use RepositoryPaginatorTrait;

    /**
     * @param $achievementId
     * @param $filters
     * @param int $currentPage
     * @param int $perPage
     * @return \Doctrine\ORM\Tools\Pagination\Paginator
     */
    public function getUserAchievements($achievementId, $filters, $currentPage = 1, $perPage = 20)
    {
        $qb = $this->createQueryBuilder('a');

        $qb->select('a');

        $qb
            ->where($qb->expr()->eq('a.achievement', ':achievementId'))
            ->setParameter('achievementId', $achievementId)
        ;

        $paginator = $this->paginate($qb, $currentPage, $perPage);

        return $paginator;
    }
}
