<?php

namespace DocumentBundle\Repository;

/**
 * ActivityEventsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ActivityEventsRepository extends \Doctrine\ORM\EntityRepository
{

}