<?php

namespace DocumentBundle\Repository;

/**
 * DocumentFileRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DocumentFileRepository extends \Doctrine\ORM\EntityRepository
{

}