<?php

namespace DocumentBundle\Repository;

/**
 * DocumentRevisionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DocumentRevisionRepository extends \Doctrine\ORM\EntityRepository
{

}