<?php

namespace DocumentBundle\Repository;

/**
 * DocumentCommentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DocumentCommentRepository extends \Doctrine\ORM\EntityRepository
{

}