<?php

namespace DocumentBundle\Repository;

/**
 * TechnicalMapCommentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TechnicalMapCommentRepository extends \Doctrine\ORM\EntityRepository
{

}