<?php

namespace DocumentBundle\Repository;

/**
 * TechnicalMapSignatoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TechnicalMapSignatoryRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @param $technicalMapId
     * @param $signatories
     * @return array
     */
    public function findDeletedSignatories($technicalMapId, $signatories)
    {
        $qb = $this->createQueryBuilder('s');
        $qb
            ->select('s')
            ->andWhere($qb->expr()->eq('s.technicalMap', $technicalMapId))
            ->andWhere($qb->expr()->notIn('s.signatory', $signatories));

        return $qb->getQuery()->getResult();
    }
}