<?php

namespace DocumentBundle\Repository;

/**
 * TechnicalMapFileRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TechnicalMapFileRepository extends \Doctrine\ORM\EntityRepository
{

}