<?php

namespace DocumentBundle\Repository;

/**
 * TechnicalMapSolutionsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TechnicalMapSolutionsRepository extends \Doctrine\ORM\EntityRepository
{

}