<?php
/**
 * Created by PhpStorm.
 * User: mazitovtr
 * Date: 07.02.19
 * Time: 9:19
 */

namespace ProductionBundle\Repository;

/**
 * SerialCategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SerialCategoryRepository extends \Doctrine\ORM\EntityRepository
{

}