<?php

namespace ProductionBundle\Repository;
use AppBundle\Traits\RepositoryPaginatorTrait;
use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * ToolRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ToolRepository extends \Doctrine\ORM\EntityRepository
{
    use RepositoryPaginatorTrait;

    /**
     * @param $filters
     * @param int $currentPage
     * @param $perPage
     * @return Paginator
     */
    public function getTools($filters, $currentPage = 1, $perPage = 20)
    {
        $qb = $this->createQueryBuilder('t');

        $qb->select('t');

        $paginator = $this->paginate($qb, $currentPage, $perPage);

        return $paginator;
    }
}
