<?php

namespace Application\Migrations;

use Doctrine\Migrations\AbstractMigration;
use Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
class Version20180726122517 extends AbstractMigration
{
    /**
     * @param Schema $schema
     */
    public function up(Schema $schema) : void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() !== 'mysql', 'Migration can only be executed safely on \'mysql\'.');

        $this->addSql('CREATE TABLE achievement (id INT AUTO_INCREMENT NOT NULL, title VARCHAR(255) NOT NULL, description LONGTEXT NOT NULL, imageUrl VARCHAR(255) NOT NULL, is_basic TINYINT(1) DEFAULT NULL, points DOUBLE PRECISION NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE client (id INT AUTO_INCREMENT NOT NULL, legal_name LONGTEXT NOT NULL, short_name VARCHAR(255) NOT NULL, UNIQUE INDEX UNIQ_C74404553EE4B093 (short_name), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE cost (id INT AUTO_INCREMENT NOT NULL, project_id INT DEFAULT NULL, owner_id INT DEFAULT NULL, title LONGTEXT NOT NULL, amount DOUBLE PRECISION NOT NULL, payment_type VARCHAR(255) DEFAULT NULL, category VARCHAR(255) DEFAULT NULL, created_at DATETIME DEFAULT NULL, deleted TINYINT(1) DEFAULT NULL, INDEX IDX_182694FC166D1F9C (project_id), INDEX IDX_182694FC7E3C61F9 (owner_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE project_file (id INT AUTO_INCREMENT NOT NULL, owner_id INT DEFAULT NULL, project_id INT DEFAULT NULL, task_id INT DEFAULT NULL, file_size VARCHAR(255) NOT NULL, format VARCHAR(255) NOT NULL, uploaded_at DATETIME NOT NULL, deleted TINYINT(1) DEFAULT NULL, file_name LONGTEXT NOT NULL, stored_file_name LONGTEXT NOT NULL, stored_preview_file_name LONGTEXT DEFAULT NULL, stored_file_dir LONGTEXT DEFAULT NULL, discriminator VARCHAR(255) NOT NULL, INDEX IDX_B50EFE087E3C61F9 (owner_id), INDEX IDX_B50EFE08166D1F9C (project_id), INDEX IDX_B50EFE088DB60186 (task_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE fos_user_group (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(180) NOT NULL, roles LONGTEXT NOT NULL COMMENT \'(DC2Type:array)\', UNIQUE INDEX UNIQ_583D1F3E5E237E06 (name), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE it_request (id INT AUTO_INCREMENT NOT NULL, owner_id INT DEFAULT NULL, assignee_id INT DEFAULT NULL, task_id INT DEFAULT NULL, title VARCHAR(255) NOT NULL, description LONGTEXT NOT NULL, created_at DATETIME NOT NULL, closed_at DATETIME DEFAULT NULL, status INT NOT NULL, INDEX IDX_49CA649E7E3C61F9 (owner_id), INDEX IDX_49CA649E59EC7D60 (assignee_id), INDEX IDX_49CA649E8DB60186 (task_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE person (id INT AUTO_INCREMENT NOT NULL, client_id INT DEFAULT NULL, email VARCHAR(180) NOT NULL, phone VARCHAR(64) NOT NULL, firstname VARCHAR(64) NOT NULL, middlename VARCHAR(255) NOT NULL, lastname VARCHAR(64) NOT NULL, role VARCHAR(255) NOT NULL, INDEX IDX_34DCD17619EB6921 (client_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE project (id INT AUTO_INCREMENT NOT NULL, team_id INT DEFAULT NULL, leader_id INT DEFAULT NULL, purchasing_manager INT DEFAULT NULL, project_status_id INT DEFAULT NULL, category_id INT DEFAULT NULL, client_id INT DEFAULT NULL, name VARCHAR(255) NOT NULL, code VARCHAR(255) DEFAULT NULL, type VARCHAR(255) NOT NULL, description LONGTEXT DEFAULT NULL, start_at DATETIME DEFAULT NULL, end_at DATETIME DEFAULT NULL, telegram_chat_id VARCHAR(255) DEFAULT NULL, telegram_chat_url VARCHAR(255) DEFAULT NULL, priority INT DEFAULT NULL, discriminator VARCHAR(255) NOT NULL, UNIQUE INDEX UNIQ_2FB3D0EE5E237E06 (name), UNIQUE INDEX UNIQ_2FB3D0EE41DC10D3 (telegram_chat_id), UNIQUE INDEX UNIQ_2FB3D0EE80397243 (telegram_chat_url), INDEX IDX_2FB3D0EE296CD8AE (team_id), INDEX IDX_2FB3D0EE73154ED4 (leader_id), INDEX IDX_2FB3D0EE3D226A64 (purchasing_manager), INDEX IDX_2FB3D0EE7ACB456A (project_status_id), INDEX IDX_2FB3D0EE12469DE2 (category_id), INDEX IDX_2FB3D0EE19EB6921 (client_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE project_category (id INT AUTO_INCREMENT NOT NULL, leader_id INT DEFAULT NULL, project_flow_id INT DEFAULT NULL, name LONGTEXT NOT NULL, INDEX IDX_3B02921A73154ED4 (leader_id), INDEX IDX_3B02921AE8A8017E (project_flow_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE project_flow (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE project_flow_project_stage (project_flow_id INT NOT NULL, project_stage_id INT NOT NULL, INDEX IDX_5B37E6B3E8A8017E (project_flow_id), INDEX IDX_5B37E6B31FD65A48 (project_stage_id), PRIMARY KEY(project_flow_id, project_stage_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE project_member (id INT AUTO_INCREMENT NOT NULL, member_id INT DEFAULT NULL, project_id INT DEFAULT NULL, INDEX IDX_674011327597D3FE (member_id), INDEX IDX_67401132166D1F9C (project_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE project_role (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE project_stage (id INT AUTO_INCREMENT NOT NULL, name LONGTEXT NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE project_stage_project_stages (project_stage_id INT NOT NULL, project_stages_id INT NOT NULL, INDEX IDX_F3A1C8271FD65A48 (project_stage_id), INDEX IDX_F3A1C8279F69A2DD (project_stages_id), PRIMARY KEY(project_stage_id, project_stages_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE project_stage_progress (id INT AUTO_INCREMENT NOT NULL, project_stage_id INT DEFAULT NULL, project_id INT DEFAULT NULL, responsible_user_id INT DEFAULT NULL, status VARCHAR(255) NOT NULL, start_at DATETIME DEFAULT NULL, end_at DATETIME DEFAULT NULL, INDEX IDX_C35102891FD65A48 (project_stage_id), INDEX IDX_C3510289166D1F9C (project_id), INDEX IDX_C3510289BDAD1998 (responsible_user_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE project_status (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) NOT NULL, label VARCHAR(255) NOT NULL, icon VARCHAR(255) NOT NULL, archived TINYINT(1) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE project_task (id INT AUTO_INCREMENT NOT NULL, project_stage_id INT DEFAULT NULL, epic_id INT DEFAULT NULL, project_id INT DEFAULT NULL, responsible_user_id INT DEFAULT NULL, controlling_user_id INT DEFAULT NULL, reporter_id INT DEFAULT NULL, status INT NOT NULL, priority INT NOT NULL, title VARCHAR(255) NOT NULL, type VARCHAR(255) NOT NULL, description LONGTEXT DEFAULT NULL, created_at DATETIME DEFAULT NULL, start_at DATETIME DEFAULT NULL, end_at DATETIME DEFAULT NULL, original_estimate DOUBLE PRECISION NOT NULL, remaining_estimate DOUBLE PRECISION NOT NULL, time_spent DOUBLE PRECISION NOT NULL, INDEX IDX_6BEF133D1FD65A48 (project_stage_id), INDEX IDX_6BEF133D6B71E00E (epic_id), INDEX IDX_6BEF133D166D1F9C (project_id), INDEX IDX_6BEF133DBDAD1998 (responsible_user_id), INDEX IDX_6BEF133D9DC36698 (controlling_user_id), INDEX IDX_6BEF133DE1CFE6F5 (reporter_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE tasks_subscribers (task_id INT NOT NULL, user_id INT NOT NULL, INDEX IDX_902572718DB60186 (task_id), INDEX IDX_90257271A76ED395 (user_id), PRIMARY KEY(task_id, user_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE task_comment (id INT AUTO_INCREMENT NOT NULL, owner_id INT DEFAULT NULL, task_id INT DEFAULT NULL, parent_comment_id INT DEFAULT NULL, created_at DATETIME NOT NULL, comment_text LONGTEXT NOT NULL, INDEX IDX_8B9578867E3C61F9 (owner_id), INDEX IDX_8B9578868DB60186 (task_id), INDEX IDX_8B957886BF2AF943 (parent_comment_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE task_diff (id INT AUTO_INCREMENT NOT NULL, changed_by_id INT DEFAULT NULL, task_id INT DEFAULT NULL, field VARCHAR(255) NOT NULL, old_value LONGTEXT DEFAULT NULL, new_value LONGTEXT DEFAULT NULL, updated_at DATETIME NOT NULL, INDEX IDX_36C3D3D0828AD0A0 (changed_by_id), INDEX IDX_36C3D3D08DB60186 (task_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE team (id INT AUTO_INCREMENT NOT NULL, leader_id INT DEFAULT NULL, parent_team_id INT DEFAULT NULL, title VARCHAR(255) NOT NULL, code VARCHAR(255) NOT NULL, last_purchase_id INT NOT NULL, purchases_team TINYINT(1) NOT NULL, financial_team TINYINT(1) NOT NULL, production_team TINYINT(1) NOT NULL, needs_task_approve TINYINT(1) NOT NULL, needs_team_leader_notification TINYINT(1) NOT NULL, telegram_chat_id VARCHAR(255) DEFAULT NULL, UNIQUE INDEX UNIQ_C4E0A61F41DC10D3 (telegram_chat_id), INDEX IDX_C4E0A61F73154ED4 (leader_id), INDEX IDX_C4E0A61F5B24ACE8 (parent_team_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE fos_user_user (id INT AUTO_INCREMENT NOT NULL, employee_role_id INT DEFAULT NULL, team_id INT DEFAULT NULL, submission_team INT DEFAULT NULL, username VARCHAR(180) NOT NULL, username_canonical VARCHAR(180) NOT NULL, email VARCHAR(180) NOT NULL, email_canonical VARCHAR(180) NOT NULL, enabled TINYINT(1) NOT NULL, salt VARCHAR(255) DEFAULT NULL, password VARCHAR(255) NOT NULL, last_login DATETIME DEFAULT NULL, confirmation_token VARCHAR(180) DEFAULT NULL, password_requested_at DATETIME DEFAULT NULL, roles LONGTEXT NOT NULL COMMENT \'(DC2Type:array)\', created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, date_of_birth DATETIME DEFAULT NULL, firstname VARCHAR(64) DEFAULT NULL, lastname VARCHAR(64) DEFAULT NULL, website VARCHAR(64) DEFAULT NULL, biography VARCHAR(1000) DEFAULT NULL, gender VARCHAR(1) DEFAULT NULL, locale VARCHAR(8) DEFAULT NULL, timezone VARCHAR(64) DEFAULT NULL, phone VARCHAR(64) DEFAULT NULL, facebook_uid VARCHAR(255) DEFAULT NULL, facebook_name VARCHAR(255) DEFAULT NULL, facebook_data LONGTEXT DEFAULT NULL COMMENT \'(DC2Type:json)\', twitter_uid VARCHAR(255) DEFAULT NULL, twitter_name VARCHAR(255) DEFAULT NULL, twitter_data LONGTEXT DEFAULT NULL COMMENT \'(DC2Type:json)\', gplus_uid VARCHAR(255) DEFAULT NULL, gplus_name VARCHAR(255) DEFAULT NULL, gplus_data LONGTEXT DEFAULT NULL COMMENT \'(DC2Type:json)\', token VARCHAR(255) DEFAULT NULL, two_step_code VARCHAR(255) DEFAULT NULL, telegram_chat_id INT DEFAULT NULL, telegram_username LONGTEXT DEFAULT NULL, image_url LONGTEXT DEFAULT NULL, middlename LONGTEXT DEFAULT NULL, theme LONGTEXT DEFAULT NULL, employee_status LONGTEXT DEFAULT NULL, room LONGTEXT DEFAULT NULL, employment_date DATETIME DEFAULT NULL, UNIQUE INDEX UNIQ_C560D76192FC23A8 (username_canonical), UNIQUE INDEX UNIQ_C560D761A0D96FBF (email_canonical), UNIQUE INDEX UNIQ_C560D761C05FB297 (confirmation_token), INDEX IDX_C560D761564F74A3 (employee_role_id), INDEX IDX_C560D761296CD8AE (team_id), INDEX IDX_C560D76156E6CD70 (submission_team), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE fos_user_user_group (user_id INT NOT NULL, group_id INT NOT NULL, INDEX IDX_B3C77447A76ED395 (user_id), INDEX IDX_B3C77447FE54D947 (group_id), PRIMARY KEY(user_id, group_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE user_achievement (id INT AUTO_INCREMENT NOT NULL, owner_id INT DEFAULT NULL, achievement_id INT DEFAULT NULL, created_at DATETIME DEFAULT NULL, INDEX IDX_3F68B6647E3C61F9 (owner_id), INDEX IDX_3F68B664B3EC99FE (achievement_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE work_log (id INT AUTO_INCREMENT NOT NULL, owner_id INT DEFAULT NULL, task_id INT DEFAULT NULL, logged_hours DOUBLE PRECISION NOT NULL, logged_day DATE DEFAULT NULL, created_at DATETIME NOT NULL, INDEX IDX_F5513F597E3C61F9 (owner_id), INDEX IDX_F5513F598DB60186 (task_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE purchase_request (id INT AUTO_INCREMENT NOT NULL, owner_id INT DEFAULT NULL, leader_id INT DEFAULT NULL, production_leader_id INT DEFAULT NULL, purchasing_leader_id INT DEFAULT NULL, financial_leader_id INT DEFAULT NULL, financial_manager_id INT DEFAULT NULL, purchasing_manager_id INT DEFAULT NULL, project_id INT DEFAULT NULL, request_timings_id INT DEFAULT NULL, code VARCHAR(255) NOT NULL, comment_text LONGTEXT NOT NULL, preferred_shipment_date DATETIME DEFAULT NULL, leader_approved TINYINT(1) NOT NULL, production_leader_approved TINYINT(1) NOT NULL, financial_leader_approved TINYINT(1) NOT NULL, purchasing_leader_approved TINYINT(1) NOT NULL, status VARCHAR(255) NOT NULL, priority VARCHAR(255) NOT NULL, type VARCHAR(255) NOT NULL, payment_status VARCHAR(255) DEFAULT NULL, delivery_status VARCHAR(255) DEFAULT NULL, production_status VARCHAR(255) DEFAULT NULL, created_at DATETIME DEFAULT NULL, relevance_date DATETIME DEFAULT NULL, UNIQUE INDEX UNIQ_204D45E677153098 (code), INDEX IDX_204D45E67E3C61F9 (owner_id), INDEX IDX_204D45E673154ED4 (leader_id), INDEX IDX_204D45E6D48A1F0E (production_leader_id), INDEX IDX_204D45E6A1E06E81 (purchasing_leader_id), INDEX IDX_204D45E674D5BF86 (financial_leader_id), INDEX IDX_204D45E6FD5CC44A (financial_manager_id), INDEX IDX_204D45E663ED6438 (purchasing_manager_id), INDEX IDX_204D45E6166D1F9C (project_id), INDEX IDX_204D45E68B7D7AA (request_timings_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE requests_subscribers (request_id INT NOT NULL, user_id INT NOT NULL, INDEX IDX_439E0F84427EB8A5 (request_id), INDEX IDX_439E0F84A76ED395 (user_id), PRIMARY KEY(request_id, user_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE purchase_request_category (id INT AUTO_INCREMENT NOT NULL, owner_id INT DEFAULT NULL, title LONGTEXT NOT NULL, INDEX IDX_22AD79C67E3C61F9 (owner_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE purchase_request_comment (id INT AUTO_INCREMENT NOT NULL, owner_id INT DEFAULT NULL, purchase_request_id INT DEFAULT NULL, parent_comment_id INT DEFAULT NULL, created_at DATETIME NOT NULL, comment_text LONGTEXT NOT NULL, INDEX IDX_C1B7F39F7E3C61F9 (owner_id), INDEX IDX_C1B7F39F4E4DEF6F (purchase_request_id), INDEX IDX_C1B7F39FBF2AF943 (parent_comment_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE purchase_request_diff (id INT AUTO_INCREMENT NOT NULL, changed_by_id INT DEFAULT NULL, request_id INT DEFAULT NULL, field VARCHAR(255) NOT NULL, old_value LONGTEXT DEFAULT NULL, new_value LONGTEXT DEFAULT NULL, updated_at DATETIME NOT NULL, INDEX IDX_FECD97F1828AD0A0 (changed_by_id), INDEX IDX_FECD97F1427EB8A5 (request_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE purchase_request_file (id INT AUTO_INCREMENT NOT NULL, owner_id INT DEFAULT NULL, purchase_request_id INT DEFAULT NULL, file_size VARCHAR(255) NOT NULL, type VARCHAR(255) NOT NULL, format VARCHAR(255) NOT NULL, uploaded_at DATETIME NOT NULL, deleted TINYINT(1) DEFAULT NULL, file_name LONGTEXT NOT NULL, stored_file_name LONGTEXT NOT NULL, stored_preview_file_name LONGTEXT DEFAULT NULL, stored_file_dir LONGTEXT DEFAULT NULL, INDEX IDX_3722E64A7E3C61F9 (owner_id), INDEX IDX_3722E64A4E4DEF6F (purchase_request_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE purchase_request_item (id INT AUTO_INCREMENT NOT NULL, unit_id INT DEFAULT NULL, purchase_request_category_id INT DEFAULT NULL, request_id INT DEFAULT NULL, supplier_id INT DEFAULT NULL, title LONGTEXT NOT NULL, sku LONGTEXT NOT NULL, quantity INT NOT NULL, actual_quantity INT DEFAULT NULL, price_without_vat DOUBLE PRECISION DEFAULT NULL, vat_amount DOUBLE PRECISION DEFAULT NULL, total_price DOUBLE PRECISION DEFAULT NULL, notice LONGTEXT DEFAULT NULL, preferred_shipment_date DATETIME DEFAULT NULL, price DOUBLE PRECISION DEFAULT NULL, prepayment_amount INT DEFAULT NULL, estimated_shipment_time INT DEFAULT NULL, invoice_nr LONGTEXT DEFAULT NULL, production_status LONGTEXT DEFAULT NULL, stock_status LONGTEXT DEFAULT NULL, INDEX IDX_A4A6F544F8BD700D (unit_id), INDEX IDX_A4A6F544A5F9320A (purchase_request_category_id), INDEX IDX_A4A6F544427EB8A5 (request_id), INDEX IDX_A4A6F5442ADD6D8C (supplier_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE request_movement (id INT AUTO_INCREMENT NOT NULL, request_id INT DEFAULT NULL, description LONGTEXT NOT NULL, source LONGTEXT NOT NULL, destination LONGTEXT NOT NULL, startDate DATETIME NOT NULL, endDate DATETIME NOT NULL, sendResponsible LONGTEXT NOT NULL, receiveResponsible LONGTEXT NOT NULL, needPrr TINYINT(1) DEFAULT NULL, needCargoDescription TINYINT(1) DEFAULT NULL, needCargoInsurance TINYINT(1) DEFAULT NULL, needAdditionalCargo TINYINT(1) DEFAULT NULL, INDEX IDX_1F875D2427EB8A5 (request_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE request_timings (id INT AUTO_INCREMENT NOT NULL, created_at DATETIME DEFAULT NULL, returned_to_fixing_at DATETIME DEFAULT NULL, moved_to_leader_approve_at DATETIME DEFAULT NULL, leader_approved_at DATETIME DEFAULT NULL, production_leader_approved_at DATETIME DEFAULT NULL, purchasing_leader_approved_at DATETIME DEFAULT NULL, manager_stated_work_at DATETIME DEFAULT NULL, manager_attached_invoice_at DATETIME DEFAULT NULL, manager_finished_work_at DATETIME DEFAULT NULL, manager_marked_as_delivered_at DATETIME DEFAULT NULL, financial_leader_approved_at DATETIME DEFAULT NULL, financial_manager_marked_as_paid_at DATETIME DEFAULT NULL, request_marked_as_done_at DATETIME DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE supplier (id INT AUTO_INCREMENT NOT NULL, title VARCHAR(255) NOT NULL, created_at DATETIME DEFAULT NULL, itn VARCHAR(255) DEFAULT NULL, UNIQUE INDEX UNIQ_9B2A6C7E2B36786B (title), UNIQUE INDEX UNIQ_9B2A6C7E591ED910 (itn), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE unit (id INT AUTO_INCREMENT NOT NULL, title VARCHAR(255) NOT NULL, short_title VARCHAR(255) NOT NULL, value VARCHAR(255) DEFAULT NULL, UNIQUE INDEX UNIQ_DCBB0C532B36786B (title), UNIQUE INDEX UNIQ_DCBB0C531D775834 (value), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE tool (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) NOT NULL, code VARCHAR(255) NOT NULL, description LONGTEXT DEFAULT NULL, type VARCHAR(255) NOT NULL, UNIQUE INDEX UNIQ_20F33ED177153098 (code), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE tool_work_log (id INT AUTO_INCREMENT NOT NULL, owner_id INT DEFAULT NULL, tool_id INT DEFAULT NULL, project_id INT DEFAULT NULL, designation VARCHAR(255) NOT NULL, title VARCHAR(255) NOT NULL, quantity INT NOT NULL, consumption_of_basic_materials DOUBLE PRECISION NOT NULL, support_materials_consumption DOUBLE PRECISION NOT NULL, placement DOUBLE PRECISION NOT NULL, printing_time DOUBLE PRECISION NOT NULL, INDEX IDX_1A904B7E7E3C61F9 (owner_id), INDEX IDX_1A904B7E8F7B22CC (tool_id), INDEX IDX_1A904B7E166D1F9C (project_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE document (id INT AUTO_INCREMENT NOT NULL, project_id INT DEFAULT NULL, document_template_id INT DEFAULT NULL, document_category_id INT DEFAULT NULL, owner_id INT DEFAULT NULL, supplier_id INT DEFAULT NULL, last_revision_id INT DEFAULT NULL, curator_id INT DEFAULT NULL, code VARCHAR(255) NOT NULL, type VARCHAR(255) NOT NULL, unlimited TINYINT(1) NOT NULL, contract_extension TINYINT(1) NOT NULL, period INT DEFAULT NULL, sum_document DOUBLE PRECISION DEFAULT NULL, vat DOUBLE PRECISION DEFAULT NULL, created_at DATETIME NOT NULL, update_at DATETIME NOT NULL, start_at DATETIME DEFAULT NULL, end_at DATETIME DEFAULT NULL, document_subject VARCHAR(255) NOT NULL, supplier_contract_code VARCHAR(255) DEFAULT NULL, measure_of_responsibility VARCHAR(255) NOT NULL, security VARCHAR(255) NOT NULL, UNIQUE INDEX UNIQ_D8698A7677153098 (code), INDEX IDX_D8698A76166D1F9C (project_id), INDEX IDX_D8698A76877338D2 (document_template_id), INDEX IDX_D8698A7690EFAA88 (document_category_id), INDEX IDX_D8698A767E3C61F9 (owner_id), INDEX IDX_D8698A762ADD6D8C (supplier_id), INDEX IDX_D8698A765DCC0383 (last_revision_id), INDEX IDX_D8698A76733D5B5D (curator_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE documents_subscribers (document_id INT NOT NULL, user_id INT NOT NULL, INDEX IDX_F551772DC33F7837 (document_id), INDEX IDX_F551772DA76ED395 (user_id), PRIMARY KEY(document_id, user_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE document_category (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE document_comment (id INT AUTO_INCREMENT NOT NULL, owner_id INT DEFAULT NULL, document_id INT DEFAULT NULL, parent_comment_id INT DEFAULT NULL, created_at DATETIME NOT NULL, comment_text LONGTEXT NOT NULL, INDEX IDX_301BF4B07E3C61F9 (owner_id), INDEX IDX_301BF4B0C33F7837 (document_id), INDEX IDX_301BF4B0BF2AF943 (parent_comment_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE document_diff (id INT AUTO_INCREMENT NOT NULL, changed_by_id INT DEFAULT NULL, document_id INT DEFAULT NULL, field VARCHAR(255) NOT NULL, old_value LONGTEXT DEFAULT NULL, new_value LONGTEXT DEFAULT NULL, updated_at DATETIME NOT NULL, INDEX IDX_E2C4CB38828AD0A0 (changed_by_id), INDEX IDX_E2C4CB38C33F7837 (document_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE document_revision (id INT AUTO_INCREMENT NOT NULL, document_id INT DEFAULT NULL, previous_revision_id INT DEFAULT NULL, owner_id INT DEFAULT NULL, content LONGTEXT DEFAULT NULL, version INT NOT NULL, createdAt DATETIME NOT NULL, INDEX IDX_E2A2E495C33F7837 (document_id), INDEX IDX_E2A2E4957E3C61F9 (owner_id), INDEX IDX_previous_revision_id (previous_revision_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE document_template (id INT AUTO_INCREMENT NOT NULL, code VARCHAR(255) NOT NULL, title VARCHAR(255) NOT NULL, UNIQUE INDEX UNIQ_18A1EEDA77153098 (code), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE acl_classes (id INT UNSIGNED AUTO_INCREMENT NOT NULL, class_type VARCHAR(200) NOT NULL, UNIQUE INDEX UNIQ_69DD750638A36066 (class_type), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE acl_security_identities (id INT UNSIGNED AUTO_INCREMENT NOT NULL, identifier VARCHAR(200) NOT NULL, username TINYINT(1) NOT NULL, UNIQUE INDEX UNIQ_8835EE78772E836AF85E0677 (identifier, username), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE acl_object_identities (id INT UNSIGNED AUTO_INCREMENT NOT NULL, parent_object_identity_id INT UNSIGNED DEFAULT NULL, class_id INT UNSIGNED NOT NULL, object_identifier VARCHAR(100) NOT NULL, entries_inheriting TINYINT(1) NOT NULL, UNIQUE INDEX UNIQ_9407E5494B12AD6EA000B10 (object_identifier, class_id), INDEX IDX_9407E54977FA751A (parent_object_identity_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE acl_object_identity_ancestors (object_identity_id INT UNSIGNED NOT NULL, ancestor_id INT UNSIGNED NOT NULL, INDEX IDX_825DE2993D9AB4A6 (object_identity_id), INDEX IDX_825DE299C671CEA1 (ancestor_id), PRIMARY KEY(object_identity_id, ancestor_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE acl_entries (id INT UNSIGNED AUTO_INCREMENT NOT NULL, class_id INT UNSIGNED NOT NULL, object_identity_id INT UNSIGNED DEFAULT NULL, security_identity_id INT UNSIGNED NOT NULL, field_name VARCHAR(50) DEFAULT NULL, ace_order SMALLINT UNSIGNED NOT NULL, mask INT NOT NULL, granting TINYINT(1) NOT NULL, granting_strategy VARCHAR(30) NOT NULL, audit_success TINYINT(1) NOT NULL, audit_failure TINYINT(1) NOT NULL, UNIQUE INDEX UNIQ_46C8B806EA000B103D9AB4A64DEF17BCE4289BF4 (class_id, object_identity_id, field_name, ace_order), INDEX IDX_46C8B806EA000B103D9AB4A6DF9183C9 (class_id, object_identity_id, security_identity_id), INDEX IDX_46C8B806EA000B10 (class_id), INDEX IDX_46C8B8063D9AB4A6 (object_identity_id), INDEX IDX_46C8B806DF9183C9 (security_identity_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('ALTER TABLE cost ADD CONSTRAINT FK_182694FC166D1F9C FOREIGN KEY (project_id) REFERENCES project (id)');
        $this->addSql('ALTER TABLE cost ADD CONSTRAINT FK_182694FC7E3C61F9 FOREIGN KEY (owner_id) REFERENCES fos_user_user (id)');
        $this->addSql('ALTER TABLE project_file ADD CONSTRAINT FK_B50EFE087E3C61F9 FOREIGN KEY (owner_id) REFERENCES fos_user_user (id)');
        $this->addSql('ALTER TABLE project_file ADD CONSTRAINT FK_B50EFE08166D1F9C FOREIGN KEY (project_id) REFERENCES project (id)');
        $this->addSql('ALTER TABLE project_file ADD CONSTRAINT FK_B50EFE088DB60186 FOREIGN KEY (task_id) REFERENCES project_task (id)');
        $this->addSql('ALTER TABLE it_request ADD CONSTRAINT FK_49CA649E7E3C61F9 FOREIGN KEY (owner_id) REFERENCES fos_user_user (id)');
        $this->addSql('ALTER TABLE it_request ADD CONSTRAINT FK_49CA649E59EC7D60 FOREIGN KEY (assignee_id) REFERENCES fos_user_user (id)');
        $this->addSql('ALTER TABLE it_request ADD CONSTRAINT FK_49CA649E8DB60186 FOREIGN KEY (task_id) REFERENCES project_task (id)');
        $this->addSql('ALTER TABLE person ADD CONSTRAINT FK_34DCD17619EB6921 FOREIGN KEY (client_id) REFERENCES client (id)');
        $this->addSql('ALTER TABLE project ADD CONSTRAINT FK_2FB3D0EE296CD8AE FOREIGN KEY (team_id) REFERENCES team (id)');
        $this->addSql('ALTER TABLE project ADD CONSTRAINT FK_2FB3D0EE73154ED4 FOREIGN KEY (leader_id) REFERENCES fos_user_user (id)');
        $this->addSql('ALTER TABLE project ADD CONSTRAINT FK_2FB3D0EE3D226A64 FOREIGN KEY (purchasing_manager) REFERENCES fos_user_user (id)');
        $this->addSql('ALTER TABLE project ADD CONSTRAINT FK_2FB3D0EE7ACB456A FOREIGN KEY (project_status_id) REFERENCES project_status (id)');
        $this->addSql('ALTER TABLE project ADD CONSTRAINT FK_2FB3D0EE12469DE2 FOREIGN KEY (category_id) REFERENCES project_category (id)');
        $this->addSql('ALTER TABLE project ADD CONSTRAINT FK_2FB3D0EE19EB6921 FOREIGN KEY (client_id) REFERENCES client (id)');
        $this->addSql('ALTER TABLE project_category ADD CONSTRAINT FK_3B02921A73154ED4 FOREIGN KEY (leader_id) REFERENCES fos_user_user (id)');
        $this->addSql('ALTER TABLE project_category ADD CONSTRAINT FK_3B02921AE8A8017E FOREIGN KEY (project_flow_id) REFERENCES project_flow (id)');
        $this->addSql('ALTER TABLE project_flow_project_stage ADD CONSTRAINT FK_5B37E6B3E8A8017E FOREIGN KEY (project_flow_id) REFERENCES project_flow (id)');
        $this->addSql('ALTER TABLE project_flow_project_stage ADD CONSTRAINT FK_5B37E6B31FD65A48 FOREIGN KEY (project_stage_id) REFERENCES project_stage (id)');
        $this->addSql('ALTER TABLE project_member ADD CONSTRAINT FK_674011327597D3FE FOREIGN KEY (member_id) REFERENCES fos_user_user (id)');
        $this->addSql('ALTER TABLE project_member ADD CONSTRAINT FK_67401132166D1F9C FOREIGN KEY (project_id) REFERENCES project (id)');
        $this->addSql('ALTER TABLE project_stage_project_stages ADD CONSTRAINT FK_F3A1C8271FD65A48 FOREIGN KEY (project_stage_id) REFERENCES project_stage (id)');
        $this->addSql('ALTER TABLE project_stage_project_stages ADD CONSTRAINT FK_F3A1C8279F69A2DD FOREIGN KEY (project_stages_id) REFERENCES project_stage (id)');
        $this->addSql('ALTER TABLE project_stage_progress ADD CONSTRAINT FK_C35102891FD65A48 FOREIGN KEY (project_stage_id) REFERENCES project_stage (id)');
        $this->addSql('ALTER TABLE project_stage_progress ADD CONSTRAINT FK_C3510289166D1F9C FOREIGN KEY (project_id) REFERENCES project (id)');
        $this->addSql('ALTER TABLE project_stage_progress ADD CONSTRAINT FK_C3510289BDAD1998 FOREIGN KEY (responsible_user_id) REFERENCES fos_user_user (id)');
        $this->addSql('ALTER TABLE project_task ADD CONSTRAINT FK_6BEF133D1FD65A48 FOREIGN KEY (project_stage_id) REFERENCES project_stage (id)');
        $this->addSql('ALTER TABLE project_task ADD CONSTRAINT FK_6BEF133D6B71E00E FOREIGN KEY (epic_id) REFERENCES project_task (id)');
        $this->addSql('ALTER TABLE project_task ADD CONSTRAINT FK_6BEF133D166D1F9C FOREIGN KEY (project_id) REFERENCES project (id)');
        $this->addSql('ALTER TABLE project_task ADD CONSTRAINT FK_6BEF133DBDAD1998 FOREIGN KEY (responsible_user_id) REFERENCES fos_user_user (id)');
        $this->addSql('ALTER TABLE project_task ADD CONSTRAINT FK_6BEF133D9DC36698 FOREIGN KEY (controlling_user_id) REFERENCES fos_user_user (id)');
        $this->addSql('ALTER TABLE project_task ADD CONSTRAINT FK_6BEF133DE1CFE6F5 FOREIGN KEY (reporter_id) REFERENCES fos_user_user (id)');
        $this->addSql('ALTER TABLE tasks_subscribers ADD CONSTRAINT FK_902572718DB60186 FOREIGN KEY (task_id) REFERENCES project_task (id)');
        $this->addSql('ALTER TABLE tasks_subscribers ADD CONSTRAINT FK_90257271A76ED395 FOREIGN KEY (user_id) REFERENCES fos_user_user (id)');
        $this->addSql('ALTER TABLE task_comment ADD CONSTRAINT FK_8B9578867E3C61F9 FOREIGN KEY (owner_id) REFERENCES fos_user_user (id)');
        $this->addSql('ALTER TABLE task_comment ADD CONSTRAINT FK_8B9578868DB60186 FOREIGN KEY (task_id) REFERENCES project_task (id)');
        $this->addSql('ALTER TABLE task_comment ADD CONSTRAINT FK_8B957886BF2AF943 FOREIGN KEY (parent_comment_id) REFERENCES task_comment (id)');
        $this->addSql('ALTER TABLE task_diff ADD CONSTRAINT FK_36C3D3D0828AD0A0 FOREIGN KEY (changed_by_id) REFERENCES fos_user_user (id)');
        $this->addSql('ALTER TABLE task_diff ADD CONSTRAINT FK_36C3D3D08DB60186 FOREIGN KEY (task_id) REFERENCES project_task (id)');
        $this->addSql('ALTER TABLE team ADD CONSTRAINT FK_C4E0A61F73154ED4 FOREIGN KEY (leader_id) REFERENCES fos_user_user (id)');
        $this->addSql('ALTER TABLE team ADD CONSTRAINT FK_C4E0A61F5B24ACE8 FOREIGN KEY (parent_team_id) REFERENCES team (id)');
        $this->addSql('ALTER TABLE fos_user_user ADD CONSTRAINT FK_C560D761564F74A3 FOREIGN KEY (employee_role_id) REFERENCES project_role (id)');
        $this->addSql('ALTER TABLE fos_user_user ADD CONSTRAINT FK_C560D761296CD8AE FOREIGN KEY (team_id) REFERENCES team (id)');
        $this->addSql('ALTER TABLE fos_user_user ADD CONSTRAINT FK_C560D76156E6CD70 FOREIGN KEY (submission_team) REFERENCES team (id)');
        $this->addSql('ALTER TABLE fos_user_user_group ADD CONSTRAINT FK_B3C77447A76ED395 FOREIGN KEY (user_id) REFERENCES fos_user_user (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE fos_user_user_group ADD CONSTRAINT FK_B3C77447FE54D947 FOREIGN KEY (group_id) REFERENCES fos_user_group (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE user_achievement ADD CONSTRAINT FK_3F68B6647E3C61F9 FOREIGN KEY (owner_id) REFERENCES fos_user_user (id)');
        $this->addSql('ALTER TABLE user_achievement ADD CONSTRAINT FK_3F68B664B3EC99FE FOREIGN KEY (achievement_id) REFERENCES achievement (id)');
        $this->addSql('ALTER TABLE work_log ADD CONSTRAINT FK_F5513F597E3C61F9 FOREIGN KEY (owner_id) REFERENCES fos_user_user (id)');
        $this->addSql('ALTER TABLE work_log ADD CONSTRAINT FK_F5513F598DB60186 FOREIGN KEY (task_id) REFERENCES project_task (id)');
        $this->addSql('ALTER TABLE purchase_request ADD CONSTRAINT FK_204D45E67E3C61F9 FOREIGN KEY (owner_id) REFERENCES fos_user_user (id)');
        $this->addSql('ALTER TABLE purchase_request ADD CONSTRAINT FK_204D45E673154ED4 FOREIGN KEY (leader_id) REFERENCES fos_user_user (id)');
        $this->addSql('ALTER TABLE purchase_request ADD CONSTRAINT FK_204D45E6D48A1F0E FOREIGN KEY (production_leader_id) REFERENCES fos_user_user (id)');
        $this->addSql('ALTER TABLE purchase_request ADD CONSTRAINT FK_204D45E6A1E06E81 FOREIGN KEY (purchasing_leader_id) REFERENCES fos_user_user (id)');
        $this->addSql('ALTER TABLE purchase_request ADD CONSTRAINT FK_204D45E674D5BF86 FOREIGN KEY (financial_leader_id) REFERENCES fos_user_user (id)');
        $this->addSql('ALTER TABLE purchase_request ADD CONSTRAINT FK_204D45E6FD5CC44A FOREIGN KEY (financial_manager_id) REFERENCES fos_user_user (id)');
        $this->addSql('ALTER TABLE purchase_request ADD CONSTRAINT FK_204D45E663ED6438 FOREIGN KEY (purchasing_manager_id) REFERENCES fos_user_user (id)');
        $this->addSql('ALTER TABLE purchase_request ADD CONSTRAINT FK_204D45E6166D1F9C FOREIGN KEY (project_id) REFERENCES project (id)');
        $this->addSql('ALTER TABLE purchase_request ADD CONSTRAINT FK_204D45E68B7D7AA FOREIGN KEY (request_timings_id) REFERENCES request_timings (id)');
        $this->addSql('ALTER TABLE requests_subscribers ADD CONSTRAINT FK_439E0F84427EB8A5 FOREIGN KEY (request_id) REFERENCES purchase_request (id)');
        $this->addSql('ALTER TABLE requests_subscribers ADD CONSTRAINT FK_439E0F84A76ED395 FOREIGN KEY (user_id) REFERENCES fos_user_user (id)');
        $this->addSql('ALTER TABLE purchase_request_category ADD CONSTRAINT FK_22AD79C67E3C61F9 FOREIGN KEY (owner_id) REFERENCES fos_user_user (id)');
        $this->addSql('ALTER TABLE purchase_request_comment ADD CONSTRAINT FK_C1B7F39F7E3C61F9 FOREIGN KEY (owner_id) REFERENCES fos_user_user (id)');
        $this->addSql('ALTER TABLE purchase_request_comment ADD CONSTRAINT FK_C1B7F39F4E4DEF6F FOREIGN KEY (purchase_request_id) REFERENCES purchase_request (id)');
        $this->addSql('ALTER TABLE purchase_request_comment ADD CONSTRAINT FK_C1B7F39FBF2AF943 FOREIGN KEY (parent_comment_id) REFERENCES purchase_request_comment (id)');
        $this->addSql('ALTER TABLE purchase_request_diff ADD CONSTRAINT FK_FECD97F1828AD0A0 FOREIGN KEY (changed_by_id) REFERENCES fos_user_user (id)');
        $this->addSql('ALTER TABLE purchase_request_diff ADD CONSTRAINT FK_FECD97F1427EB8A5 FOREIGN KEY (request_id) REFERENCES purchase_request (id)');
        $this->addSql('ALTER TABLE purchase_request_file ADD CONSTRAINT FK_3722E64A7E3C61F9 FOREIGN KEY (owner_id) REFERENCES fos_user_user (id)');
        $this->addSql('ALTER TABLE purchase_request_file ADD CONSTRAINT FK_3722E64A4E4DEF6F FOREIGN KEY (purchase_request_id) REFERENCES purchase_request (id)');
        $this->addSql('ALTER TABLE purchase_request_item ADD CONSTRAINT FK_A4A6F544F8BD700D FOREIGN KEY (unit_id) REFERENCES unit (id)');
        $this->addSql('ALTER TABLE purchase_request_item ADD CONSTRAINT FK_A4A6F544A5F9320A FOREIGN KEY (purchase_request_category_id) REFERENCES purchase_request_category (id)');
        $this->addSql('ALTER TABLE purchase_request_item ADD CONSTRAINT FK_A4A6F544427EB8A5 FOREIGN KEY (request_id) REFERENCES purchase_request (id)');
        $this->addSql('ALTER TABLE purchase_request_item ADD CONSTRAINT FK_A4A6F5442ADD6D8C FOREIGN KEY (supplier_id) REFERENCES supplier (id)');
        $this->addSql('ALTER TABLE request_movement ADD CONSTRAINT FK_1F875D2427EB8A5 FOREIGN KEY (request_id) REFERENCES purchase_request (id)');
        $this->addSql('ALTER TABLE tool_work_log ADD CONSTRAINT FK_1A904B7E7E3C61F9 FOREIGN KEY (owner_id) REFERENCES fos_user_user (id)');
        $this->addSql('ALTER TABLE tool_work_log ADD CONSTRAINT FK_1A904B7E8F7B22CC FOREIGN KEY (tool_id) REFERENCES tool (id)');
        $this->addSql('ALTER TABLE tool_work_log ADD CONSTRAINT FK_1A904B7E166D1F9C FOREIGN KEY (project_id) REFERENCES project (id)');
        $this->addSql('ALTER TABLE document ADD CONSTRAINT FK_D8698A76166D1F9C FOREIGN KEY (project_id) REFERENCES project (id)');
        $this->addSql('ALTER TABLE document ADD CONSTRAINT FK_D8698A76877338D2 FOREIGN KEY (document_template_id) REFERENCES document_template (id)');
        $this->addSql('ALTER TABLE document ADD CONSTRAINT FK_D8698A7690EFAA88 FOREIGN KEY (document_category_id) REFERENCES document_category (id)');
        $this->addSql('ALTER TABLE document ADD CONSTRAINT FK_D8698A767E3C61F9 FOREIGN KEY (owner_id) REFERENCES fos_user_user (id)');
        $this->addSql('ALTER TABLE document ADD CONSTRAINT FK_D8698A762ADD6D8C FOREIGN KEY (supplier_id) REFERENCES supplier (id)');
        $this->addSql('ALTER TABLE document ADD CONSTRAINT FK_D8698A765DCC0383 FOREIGN KEY (last_revision_id) REFERENCES document_revision (id)');
        $this->addSql('ALTER TABLE document ADD CONSTRAINT FK_D8698A76733D5B5D FOREIGN KEY (curator_id) REFERENCES fos_user_user (id)');
        $this->addSql('ALTER TABLE documents_subscribers ADD CONSTRAINT FK_F551772DC33F7837 FOREIGN KEY (document_id) REFERENCES document (id)');
        $this->addSql('ALTER TABLE documents_subscribers ADD CONSTRAINT FK_F551772DA76ED395 FOREIGN KEY (user_id) REFERENCES fos_user_user (id)');
        $this->addSql('ALTER TABLE document_comment ADD CONSTRAINT FK_301BF4B07E3C61F9 FOREIGN KEY (owner_id) REFERENCES fos_user_user (id)');
        $this->addSql('ALTER TABLE document_comment ADD CONSTRAINT FK_301BF4B0C33F7837 FOREIGN KEY (document_id) REFERENCES document (id)');
        $this->addSql('ALTER TABLE document_comment ADD CONSTRAINT FK_301BF4B0BF2AF943 FOREIGN KEY (parent_comment_id) REFERENCES document_comment (id)');
        $this->addSql('ALTER TABLE document_diff ADD CONSTRAINT FK_E2C4CB38828AD0A0 FOREIGN KEY (changed_by_id) REFERENCES fos_user_user (id)');
        $this->addSql('ALTER TABLE document_diff ADD CONSTRAINT FK_E2C4CB38C33F7837 FOREIGN KEY (document_id) REFERENCES document (id)');
        $this->addSql('ALTER TABLE document_revision ADD CONSTRAINT FK_E2A2E495C33F7837 FOREIGN KEY (document_id) REFERENCES document (id)');
        $this->addSql('ALTER TABLE document_revision ADD CONSTRAINT FK_E2A2E495AF3077E5 FOREIGN KEY (previous_revision_id) REFERENCES document_revision (id)');
        $this->addSql('ALTER TABLE document_revision ADD CONSTRAINT FK_E2A2E4957E3C61F9 FOREIGN KEY (owner_id) REFERENCES fos_user_user (id)');
        $this->addSql('ALTER TABLE acl_object_identities ADD CONSTRAINT FK_9407E54977FA751A FOREIGN KEY (parent_object_identity_id) REFERENCES acl_object_identities (id)');
        $this->addSql('ALTER TABLE acl_object_identity_ancestors ADD CONSTRAINT FK_825DE2993D9AB4A6 FOREIGN KEY (object_identity_id) REFERENCES acl_object_identities (id) ON UPDATE CASCADE ON DELETE CASCADE');
        $this->addSql('ALTER TABLE acl_object_identity_ancestors ADD CONSTRAINT FK_825DE299C671CEA1 FOREIGN KEY (ancestor_id) REFERENCES acl_object_identities (id) ON UPDATE CASCADE ON DELETE CASCADE');
        $this->addSql('ALTER TABLE acl_entries ADD CONSTRAINT FK_46C8B806EA000B10 FOREIGN KEY (class_id) REFERENCES acl_classes (id) ON UPDATE CASCADE ON DELETE CASCADE');
        $this->addSql('ALTER TABLE acl_entries ADD CONSTRAINT FK_46C8B8063D9AB4A6 FOREIGN KEY (object_identity_id) REFERENCES acl_object_identities (id) ON UPDATE CASCADE ON DELETE CASCADE');
        $this->addSql('ALTER TABLE acl_entries ADD CONSTRAINT FK_46C8B806DF9183C9 FOREIGN KEY (security_identity_id) REFERENCES acl_security_identities (id) ON UPDATE CASCADE ON DELETE CASCADE');
    }

    /**
     * @param Schema $schema
     */
    public function down(Schema $schema) : void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() !== 'mysql', 'Migration can only be executed safely on \'mysql\'.');

        $this->addSql('ALTER TABLE user_achievement DROP FOREIGN KEY FK_3F68B664B3EC99FE');
        $this->addSql('ALTER TABLE person DROP FOREIGN KEY FK_34DCD17619EB6921');
        $this->addSql('ALTER TABLE project DROP FOREIGN KEY FK_2FB3D0EE19EB6921');
        $this->addSql('ALTER TABLE fos_user_user_group DROP FOREIGN KEY FK_B3C77447FE54D947');
        $this->addSql('ALTER TABLE cost DROP FOREIGN KEY FK_182694FC166D1F9C');
        $this->addSql('ALTER TABLE project_file DROP FOREIGN KEY FK_B50EFE08166D1F9C');
        $this->addSql('ALTER TABLE project_member DROP FOREIGN KEY FK_67401132166D1F9C');
        $this->addSql('ALTER TABLE project_stage_progress DROP FOREIGN KEY FK_C3510289166D1F9C');
        $this->addSql('ALTER TABLE project_task DROP FOREIGN KEY FK_6BEF133D166D1F9C');
        $this->addSql('ALTER TABLE purchase_request DROP FOREIGN KEY FK_204D45E6166D1F9C');
        $this->addSql('ALTER TABLE tool_work_log DROP FOREIGN KEY FK_1A904B7E166D1F9C');
        $this->addSql('ALTER TABLE document DROP FOREIGN KEY FK_D8698A76166D1F9C');
        $this->addSql('ALTER TABLE project DROP FOREIGN KEY FK_2FB3D0EE12469DE2');
        $this->addSql('ALTER TABLE project_category DROP FOREIGN KEY FK_3B02921AE8A8017E');
        $this->addSql('ALTER TABLE project_flow_project_stage DROP FOREIGN KEY FK_5B37E6B3E8A8017E');
        $this->addSql('ALTER TABLE fos_user_user DROP FOREIGN KEY FK_C560D761564F74A3');
        $this->addSql('ALTER TABLE project_flow_project_stage DROP FOREIGN KEY FK_5B37E6B31FD65A48');
        $this->addSql('ALTER TABLE project_stage_project_stages DROP FOREIGN KEY FK_F3A1C8271FD65A48');
        $this->addSql('ALTER TABLE project_stage_project_stages DROP FOREIGN KEY FK_F3A1C8279F69A2DD');
        $this->addSql('ALTER TABLE project_stage_progress DROP FOREIGN KEY FK_C35102891FD65A48');
        $this->addSql('ALTER TABLE project_task DROP FOREIGN KEY FK_6BEF133D1FD65A48');
        $this->addSql('ALTER TABLE project DROP FOREIGN KEY FK_2FB3D0EE7ACB456A');
        $this->addSql('ALTER TABLE project_file DROP FOREIGN KEY FK_B50EFE088DB60186');
        $this->addSql('ALTER TABLE it_request DROP FOREIGN KEY FK_49CA649E8DB60186');
        $this->addSql('ALTER TABLE project_task DROP FOREIGN KEY FK_6BEF133D6B71E00E');
        $this->addSql('ALTER TABLE tasks_subscribers DROP FOREIGN KEY FK_902572718DB60186');
        $this->addSql('ALTER TABLE task_comment DROP FOREIGN KEY FK_8B9578868DB60186');
        $this->addSql('ALTER TABLE task_diff DROP FOREIGN KEY FK_36C3D3D08DB60186');
        $this->addSql('ALTER TABLE work_log DROP FOREIGN KEY FK_F5513F598DB60186');
        $this->addSql('ALTER TABLE task_comment DROP FOREIGN KEY FK_8B957886BF2AF943');
        $this->addSql('ALTER TABLE project DROP FOREIGN KEY FK_2FB3D0EE296CD8AE');
        $this->addSql('ALTER TABLE team DROP FOREIGN KEY FK_C4E0A61F5B24ACE8');
        $this->addSql('ALTER TABLE fos_user_user DROP FOREIGN KEY FK_C560D761296CD8AE');
        $this->addSql('ALTER TABLE fos_user_user DROP FOREIGN KEY FK_C560D76156E6CD70');
        $this->addSql('ALTER TABLE cost DROP FOREIGN KEY FK_182694FC7E3C61F9');
        $this->addSql('ALTER TABLE project_file DROP FOREIGN KEY FK_B50EFE087E3C61F9');
        $this->addSql('ALTER TABLE it_request DROP FOREIGN KEY FK_49CA649E7E3C61F9');
        $this->addSql('ALTER TABLE it_request DROP FOREIGN KEY FK_49CA649E59EC7D60');
        $this->addSql('ALTER TABLE project DROP FOREIGN KEY FK_2FB3D0EE73154ED4');
        $this->addSql('ALTER TABLE project DROP FOREIGN KEY FK_2FB3D0EE3D226A64');
        $this->addSql('ALTER TABLE project_category DROP FOREIGN KEY FK_3B02921A73154ED4');
        $this->addSql('ALTER TABLE project_member DROP FOREIGN KEY FK_674011327597D3FE');
        $this->addSql('ALTER TABLE project_stage_progress DROP FOREIGN KEY FK_C3510289BDAD1998');
        $this->addSql('ALTER TABLE project_task DROP FOREIGN KEY FK_6BEF133DBDAD1998');
        $this->addSql('ALTER TABLE project_task DROP FOREIGN KEY FK_6BEF133D9DC36698');
        $this->addSql('ALTER TABLE project_task DROP FOREIGN KEY FK_6BEF133DE1CFE6F5');
        $this->addSql('ALTER TABLE tasks_subscribers DROP FOREIGN KEY FK_90257271A76ED395');
        $this->addSql('ALTER TABLE task_comment DROP FOREIGN KEY FK_8B9578867E3C61F9');
        $this->addSql('ALTER TABLE task_diff DROP FOREIGN KEY FK_36C3D3D0828AD0A0');
        $this->addSql('ALTER TABLE team DROP FOREIGN KEY FK_C4E0A61F73154ED4');
        $this->addSql('ALTER TABLE fos_user_user_group DROP FOREIGN KEY FK_B3C77447A76ED395');
        $this->addSql('ALTER TABLE user_achievement DROP FOREIGN KEY FK_3F68B6647E3C61F9');
        $this->addSql('ALTER TABLE work_log DROP FOREIGN KEY FK_F5513F597E3C61F9');
        $this->addSql('ALTER TABLE purchase_request DROP FOREIGN KEY FK_204D45E67E3C61F9');
        $this->addSql('ALTER TABLE purchase_request DROP FOREIGN KEY FK_204D45E673154ED4');
        $this->addSql('ALTER TABLE purchase_request DROP FOREIGN KEY FK_204D45E6D48A1F0E');
        $this->addSql('ALTER TABLE purchase_request DROP FOREIGN KEY FK_204D45E6A1E06E81');
        $this->addSql('ALTER TABLE purchase_request DROP FOREIGN KEY FK_204D45E674D5BF86');
        $this->addSql('ALTER TABLE purchase_request DROP FOREIGN KEY FK_204D45E6FD5CC44A');
        $this->addSql('ALTER TABLE purchase_request DROP FOREIGN KEY FK_204D45E663ED6438');
        $this->addSql('ALTER TABLE requests_subscribers DROP FOREIGN KEY FK_439E0F84A76ED395');
        $this->addSql('ALTER TABLE purchase_request_category DROP FOREIGN KEY FK_22AD79C67E3C61F9');
        $this->addSql('ALTER TABLE purchase_request_comment DROP FOREIGN KEY FK_C1B7F39F7E3C61F9');
        $this->addSql('ALTER TABLE purchase_request_diff DROP FOREIGN KEY FK_FECD97F1828AD0A0');
        $this->addSql('ALTER TABLE purchase_request_file DROP FOREIGN KEY FK_3722E64A7E3C61F9');
        $this->addSql('ALTER TABLE tool_work_log DROP FOREIGN KEY FK_1A904B7E7E3C61F9');
        $this->addSql('ALTER TABLE document DROP FOREIGN KEY FK_D8698A767E3C61F9');
        $this->addSql('ALTER TABLE document DROP FOREIGN KEY FK_D8698A76733D5B5D');
        $this->addSql('ALTER TABLE documents_subscribers DROP FOREIGN KEY FK_F551772DA76ED395');
        $this->addSql('ALTER TABLE document_comment DROP FOREIGN KEY FK_301BF4B07E3C61F9');
        $this->addSql('ALTER TABLE document_diff DROP FOREIGN KEY FK_E2C4CB38828AD0A0');
        $this->addSql('ALTER TABLE document_revision DROP FOREIGN KEY FK_E2A2E4957E3C61F9');
        $this->addSql('ALTER TABLE requests_subscribers DROP FOREIGN KEY FK_439E0F84427EB8A5');
        $this->addSql('ALTER TABLE purchase_request_comment DROP FOREIGN KEY FK_C1B7F39F4E4DEF6F');
        $this->addSql('ALTER TABLE purchase_request_diff DROP FOREIGN KEY FK_FECD97F1427EB8A5');
        $this->addSql('ALTER TABLE purchase_request_file DROP FOREIGN KEY FK_3722E64A4E4DEF6F');
        $this->addSql('ALTER TABLE purchase_request_item DROP FOREIGN KEY FK_A4A6F544427EB8A5');
        $this->addSql('ALTER TABLE request_movement DROP FOREIGN KEY FK_1F875D2427EB8A5');
        $this->addSql('ALTER TABLE purchase_request_item DROP FOREIGN KEY FK_A4A6F544A5F9320A');
        $this->addSql('ALTER TABLE purchase_request_comment DROP FOREIGN KEY FK_C1B7F39FBF2AF943');
        $this->addSql('ALTER TABLE purchase_request DROP FOREIGN KEY FK_204D45E68B7D7AA');
        $this->addSql('ALTER TABLE purchase_request_item DROP FOREIGN KEY FK_A4A6F5442ADD6D8C');
        $this->addSql('ALTER TABLE document DROP FOREIGN KEY FK_D8698A762ADD6D8C');
        $this->addSql('ALTER TABLE purchase_request_item DROP FOREIGN KEY FK_A4A6F544F8BD700D');
        $this->addSql('ALTER TABLE tool_work_log DROP FOREIGN KEY FK_1A904B7E8F7B22CC');
        $this->addSql('ALTER TABLE documents_subscribers DROP FOREIGN KEY FK_F551772DC33F7837');
        $this->addSql('ALTER TABLE document_comment DROP FOREIGN KEY FK_301BF4B0C33F7837');
        $this->addSql('ALTER TABLE document_diff DROP FOREIGN KEY FK_E2C4CB38C33F7837');
        $this->addSql('ALTER TABLE document_revision DROP FOREIGN KEY FK_E2A2E495C33F7837');
        $this->addSql('ALTER TABLE document DROP FOREIGN KEY FK_D8698A7690EFAA88');
        $this->addSql('ALTER TABLE document_comment DROP FOREIGN KEY FK_301BF4B0BF2AF943');
        $this->addSql('ALTER TABLE document DROP FOREIGN KEY FK_D8698A765DCC0383');
        $this->addSql('ALTER TABLE document_revision DROP FOREIGN KEY FK_E2A2E495AF3077E5');
        $this->addSql('ALTER TABLE document DROP FOREIGN KEY FK_D8698A76877338D2');
        $this->addSql('ALTER TABLE acl_entries DROP FOREIGN KEY FK_46C8B806EA000B10');
        $this->addSql('ALTER TABLE acl_entries DROP FOREIGN KEY FK_46C8B806DF9183C9');
        $this->addSql('ALTER TABLE acl_object_identities DROP FOREIGN KEY FK_9407E54977FA751A');
        $this->addSql('ALTER TABLE acl_object_identity_ancestors DROP FOREIGN KEY FK_825DE2993D9AB4A6');
        $this->addSql('ALTER TABLE acl_object_identity_ancestors DROP FOREIGN KEY FK_825DE299C671CEA1');
        $this->addSql('ALTER TABLE acl_entries DROP FOREIGN KEY FK_46C8B8063D9AB4A6');
        $this->addSql('DROP TABLE achievement');
        $this->addSql('DROP TABLE client');
        $this->addSql('DROP TABLE cost');
        $this->addSql('DROP TABLE project_file');
        $this->addSql('DROP TABLE fos_user_group');
        $this->addSql('DROP TABLE it_request');
        $this->addSql('DROP TABLE person');
        $this->addSql('DROP TABLE project');
        $this->addSql('DROP TABLE project_category');
        $this->addSql('DROP TABLE project_flow');
        $this->addSql('DROP TABLE project_flow_project_stage');
        $this->addSql('DROP TABLE project_member');
        $this->addSql('DROP TABLE project_role');
        $this->addSql('DROP TABLE project_stage');
        $this->addSql('DROP TABLE project_stage_project_stages');
        $this->addSql('DROP TABLE project_stage_progress');
        $this->addSql('DROP TABLE project_status');
        $this->addSql('DROP TABLE project_task');
        $this->addSql('DROP TABLE tasks_subscribers');
        $this->addSql('DROP TABLE task_comment');
        $this->addSql('DROP TABLE task_diff');
        $this->addSql('DROP TABLE team');
        $this->addSql('DROP TABLE fos_user_user');
        $this->addSql('DROP TABLE fos_user_user_group');
        $this->addSql('DROP TABLE user_achievement');
        $this->addSql('DROP TABLE work_log');
        $this->addSql('DROP TABLE purchase_request');
        $this->addSql('DROP TABLE requests_subscribers');
        $this->addSql('DROP TABLE purchase_request_category');
        $this->addSql('DROP TABLE purchase_request_comment');
        $this->addSql('DROP TABLE purchase_request_diff');
        $this->addSql('DROP TABLE purchase_request_file');
        $this->addSql('DROP TABLE purchase_request_item');
        $this->addSql('DROP TABLE request_movement');
        $this->addSql('DROP TABLE request_timings');
        $this->addSql('DROP TABLE supplier');
        $this->addSql('DROP TABLE unit');
        $this->addSql('DROP TABLE tool');
        $this->addSql('DROP TABLE tool_work_log');
        $this->addSql('DROP TABLE document');
        $this->addSql('DROP TABLE documents_subscribers');
        $this->addSql('DROP TABLE document_category');
        $this->addSql('DROP TABLE document_comment');
        $this->addSql('DROP TABLE document_diff');
        $this->addSql('DROP TABLE document_revision');
        $this->addSql('DROP TABLE document_template');
        $this->addSql('DROP TABLE acl_classes');
        $this->addSql('DROP TABLE acl_security_identities');
        $this->addSql('DROP TABLE acl_object_identities');
        $this->addSql('DROP TABLE acl_object_identity_ancestors');
        $this->addSql('DROP TABLE acl_entries');
    }
}
