<?php
/**
 * Created by PhpStorm.
 * User: mazitovtr
 * Date: 05.02.19
 * Time: 12:28
 */

namespace PurchaseBundle\Repository;

/**
 * InvoiceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InvoiceRepository extends \Doctrine\ORM\EntityRepository
{

}