<?php

namespace PurchaseBundle\Repository;
use AppBundle\Traits\RepositoryPaginatorTrait;
use Doctrine\ORM\QueryBuilder;
use PurchaseBundle\Entity\InvoiceRegistry;
use PurchaseBundle\Entity\InvoiceRegistryDiff;

/**
 * InvoiceRegistryDiffRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InvoiceRegistryDiffRepository extends \Doctrine\ORM\EntityRepository
{
    public function getRegistryChanges(InvoiceRegistry $registry)
    {
        $qb = $this->createQueryBuilder('r');

        $qb
            ->select('r')
            ->where($qb->expr()->eq('r.invoiceRegistry', ':registryId'))
            ->setParameter('registryId', $registry->getId());

        $qb->orderBy('r.id', 'DESC');

        return $qb->getQuery()->getResult();
    }

}