<?php

namespace PurchaseBundle\Repository;

/**
 * PurchaseRequestCategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PurchaseRequestCategoryRepository extends \Doctrine\ORM\EntityRepository
{
}
