<?php

namespace PurchaseBundle\Repository;

/**
 * PurchaseRequestDeliveryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PurchaseRequestDeliveryRepository extends \Doctrine\ORM\EntityRepository
{
}
