<?php

namespace PurchaseBundle\Repository;

/**
 * PurchaseRequestCommentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PurchaseRequestCommentRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @return array
     */
    public function getLatestComments()
    {
        $qb = $this->createQueryBuilder('tc');

        $qb
            ->select('tc')
            ->andWhere(
                $qb->expr()->between('tc.createdAt', ':yesterday', ':now')
            )
            ->setParameters([
                'yesterday' => new \DateTime('yesterday 00:00:00'),
                'now' => new \DateTime('now')
            ]);

        $qb->orderBy('tc.id', 'DESC');

        return $qb->getQuery()->getResult();
    }
}
