<?php


namespace PurchaseBundle\Repository;

use AppBundle\Traits\RepositoryPaginatorTrait;

/**
 * RentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RentRepository extends \Doctrine\ORM\EntityRepository
{
    use RepositoryPaginatorTrait;

    /**
     * @param int $currentPage
     * @param int $perPage
     * @return \Doctrine\ORM\Tools\Pagination\Paginator
     */
    public function  getRent($currentPage = 1, $perPage = 20)
    {
        $qb = $this->createQueryBuilder('r');

        $qb->select('r');

        $paginator = $this->paginate($qb, $currentPage, $perPage);

        return $paginator;
    }

    /**
     * @param $tenement
     * @return mixed
     */
    public function getSupplier($tenement)
    {
        $qb = $this->createQueryBuilder('t');

        $qb->select('t');

        $qb
            ->leftJoin('t.tenement','s')
            ->andWhere('s.title = :title')
            ->setParameter('title', $tenement)
        ;

        return $qb->getQuery()->getResult();
    }
}