<?php

namespace PurchaseBundle\Repository;

/**
 * RequestTimingsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RequestTimingsRepository extends \Doctrine\ORM\EntityRepository
{
}
