<?php

namespace PurchaseBundle\Repository;

/**
 * RequestMovementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RequestMovementRepository extends \Doctrine\ORM\EntityRepository
{
}
