<?php

namespace PurchaseBundle\Repository;

/**
 * RequestFileRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RequestFileRepository extends \Doctrine\ORM\EntityRepository
{
}
