<?php

namespace PurchaseBundle\Repository;

/**
 * SupplierCommentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SupplierCommentRepository extends \Doctrine\ORM\EntityRepository
{

}