<?php

namespace PurchaseBundle\Repository;

/**
 * SupplierIncidentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SupplierIncidentRepository extends \Doctrine\ORM\EntityRepository
{
}
