<?php

namespace PurchaseBundle\Repository;

/**
 * PurchaseRequestCategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SuppliesCategoryRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @return array
     */
    public function getCategoriesGroupedByParent()
    {
        $qb = $this->createQueryBuilder('sc');
        $qb->select('sc');

        $categories = $qb->getQuery()->getResult();

        $teams = [];
        foreach ($categories as $category) {
            if ($category->getParentCategory()) {
                $teams[$category->getParentCategory()->getTitle()][] = $category;
            }
        }

        return $teams;
    }
}
