<?php

namespace PurchaseBundle\Repository;

/**
 * SupplierPersonRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SupplierPersonRepository extends \Doctrine\ORM\EntityRepository
{

}