<?php


namespace PurchaseBundle\Repository;

use AppBundle\Traits\RepositoryPaginatorTrait;

/**
 * TenementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TenementRepository extends \Doctrine\ORM\EntityRepository
{
    use RepositoryPaginatorTrait;

    /**
     * @param int $currentPage
     * @param int $perPage
     * @return \Doctrine\ORM\Tools\Pagination\Paginator
     */
    public function  getTenement($currentPage = 1, $perPage = 20)
    {
        $qb = $this->createQueryBuilder('t');

        $qb->select('t');

        $paginator = $this->paginate($qb, $currentPage, $perPage);

        return $paginator;
    }
}