<?php
/**
 * Created by PhpStorm.
 * User: shemyakinDV
 * Date: 24.02.2019
 * Time: 16:06
 */

namespace InfrastructureBundle\Repository;

/**
 * ComputerPartsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ComputerPartsRepository extends \Doctrine\ORM\EntityRepository
{

}