<?php

namespace WarehouseBundle\Repository;

/**
 * NomenclatureGroupRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NomenclatureGroupRepository extends \Doctrine\ORM\EntityRepository
{
}
